### ISSUE TITLE
tox command in README

### ISSUE THREAD

**Issue by braceal** [gpauloski/python-template#99]
### Describe the Request

The tox command in the readme was not working, so I had to modify it (shown below). Do you know if it works for a different version of tox? Or is it just a small typo?

**Current**:
```bash
tox --devenv venv -e py 310
```

**Correction**:
```bash
tox --devenv venv -e py310
```

Also just a quick question, do you usually activate the `venv` environment before running the `pre-commit install` command?
```bash
source venv/bin/activate
```

**Comment by gpauloski** [comment]
Yep! That's a typo. I'll fix it.

I do activate my virtual environment first, but that's mostly because I install pre-commit into the virtual environment rather than having it globally installed. pre-commit will make and activate it's own virtual environments when running the hooks, though, so it doesn't matter too much.

**Comment by gpauloski** [comment]
Also I'll mention that the installation/testing instructions here are pretty simple because the instructions are usually a bit different from project to projects. But my usual flow after cloning is something like:
```bash
python3.11 -m venv venv
. venv/bin/activate
pip install -e .[dev,docs]
pre-commit install
# then when testing
pre-commit run --all-files
tox -e py311
```

**Comment by braceal** [comment]
Thanks Greg! This is very helpful.
